# Generated by Django 6.0.1 on 2026-02-02 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_comment_karmatransaction_like'),
    ]

    operations = [
    ]
